Fix firefox deserialization + fix from_reader
mandrean/har-rs pull request #31
Opened 2023-08-04 08:01 UTC by grelner

This fixes two things:

1. Firefox does not write send, wait and receive in Timings. They have been changed to optional
2. from_reader was using serde_yaml instead of serde_json

2024-10-15 23:16 UTC, mandrean requested changes

2024-10-15 23:16 UTC, mandrean commented on src/v1_3/mod.rs
> +    pub receive: Option<f64>,
According to the HAR spec, `send`, `wait` and `receive` are all required fields. They even explicitly write that they are **not** optional, see:

http://www.softwareishard.com/blog/har-12-spec/#timings

![image](https://github.com/user-attachments/assets/60fbbd13-6d98-49eb-bf59-3f0efc5ede04)

2024-10-15 23:17 UTC, mandrean requested changes

2024-10-15 23:17 UTC, mandrean commented on src/v1_2/mod.rs
> +    pub receive: Option<f64>,
According to the HAR v1.2 spec, `send`, `wait` and `receive` are all required fields. They even explicitly write that they are **not** optional, see:

http://www.softwareishard.com/blog/har-12-spec/#timings

![image](https://github.com/user-attachments/assets/60fbbd13-6d98-49eb-bf59-3f0efc5ede04)

2024-10-15 23:25 UTC, mandrean commented
Hey @grelner, thanks for opening the PR!

Can the Firefox issue you're describing be solved without breaking the HAR v1.2 and v1.3 specs? `send`, `wait` and `receive` are all required fields. 

Also a test reproducing the Firefox issue would be nice.

2025-02-08 23:18 UTC, Equinox4 commented
Cannot reproduce with firefox v134, `send`, `wait` and `receive` are correctly written.

2025-02-10 09:04 UTC, mandrean commented
Thanks @Equinox4

@grelner: closing since the fields are required and the issue isn't reproducible.

2025-02-10 09:04 UTC, closed without merging